mobu-of-the-world/mobu

src/App.tsx
src/AppComponent.tsx
src/AppContainer.tsx
src/atoms/Button.tsx
src/atoms/Timer.tsx
src/index.tsx

- time watch feature
- place start/pause/reset button

implement time watch feature

---

src/AppComponent.tsx
src/AppContainer.tsx
src/atoms/Timer.tsx

- Show elapsed time in time string format instead of just a number

show elapsed time in time string format

---

src/AppComponent.tsx
src/AppContainer.tsx

- add text field to register a new user

User regist

---

src/AppComponent.tsx
src/AppContainer.tsx
src/atoms/Button.tsx

Disable empty username

---

src/AppComponent.tsx
src/AppContainer.tsx

Remove username with button click

---

src/AppContainer.tsx

This PR provides checker for blank strings and prevents to stored duplicated usernames.

Improve validation

---

src/AppComponent.tsx
src/AppContainer.tsx

Implement shuffle button

---

src/AppComponent.tsx
src/AppContainer.tsx
src/atoms/Button.tsx
src/atoms/TextInput.tsx

When settings interval as 5 sec in this screenshot.

Implement to be bottom after interval

---

src/AppComponent.tsx
src/AppContainer.tsx
src/atoms/Form.tsx

- Accept enter key to register a new user

Register user by enter key

---

src/AppComponent.tsx
src/atoms/Emoji.tsx
src/molecules/User.tsx

- Show driver/navigator indicator using Emoji

Driver indicator using Emoji

---

src/AppContainer.tsx

Start desktop notification after interval

---

src/AppComponent.tsx
src/AppContainer.tsx

Use toggle button instead of start and pause

---

src/AppContainer.tsx

Stop timer after interval

---

src/AppContainer.tsx

Or we can use any at here. I don't have strong opinion in both for now 🤔

Improve a func signature

---

src/AppComponent.tsx

Disable shuffle if it is needless

---

src/atoms/Text.tsx
src/atoms/Timer.tsx
src/index.tsx
src/molecules/Interval.tsx
src/molecules/Timer.tsx
src/organisms/Session.tsx
src/organisms/UserList.tsx
src/pages/AppContainer.tsx
src/templates/AppComponent.tsx

- Refactor to separate source files into organisms, molecules, atoms

Refactor to separate sources into organisms/molecules/atoms

---

public/index.html

- Change application name from `React App` -> `mobu`

change application name from React App -> mobu

---

package.json
src/pages/AppContainer.tsx
yarn.lock

Personally I don't think we need this feature. But @pankona want it 😁

Store user list into cookie

---

src/organisms/Session.css
src/organisms/Session.tsx
src/organisms/UserList.css
src/organisms/UserList.tsx
src/templates/AppComponent.css
src/templates/AppComponent.tsx

- Layout User list and session in two panes

layout userlist and session in two pane

---

src/atoms/MenuIcon.css
src/atoms/MenuIcon.tsx
src/molecules/Header.css
src/molecules/Header.tsx
src/molecules/Menu.css
src/molecules/Menu.tsx
src/templates/AppComponent.tsx

add header

---

src/atoms/Button.css
src/atoms/Button.tsx
src/atoms/Emoji.css
src/atoms/Emoji.tsx
src/atoms/Text.css
src/atoms/Text.tsx
src/atoms/TextInput.css
src/atoms/TextInput.tsx
src/molecules/User.css
src/molecules/User.tsx
src/organisms/UserList.css
src/organisms/UserList.tsx

adjust font-size

---

package.json
public/index.html
src/atoms/Button.css
src/atoms/Button.tsx
src/atoms/Emoji.css
src/atoms/Emoji.tsx
src/atoms/Text.css
src/atoms/TextInput.css
src/atoms/TextInput.tsx
src/index.tsx
src/molecules/Header.css
src/molecules/Header.tsx
src/molecules/Interval.css
src/molecules/Interval.tsx
src/molecules/Timer.css
src/molecules/Timer.tsx
src/molecules/User.tsx
src/molecules/UserRegister.css
src/molecules/UserRegister.tsx
src/organisms/Session.css
src/organisms/Session.tsx
src/organisms/UserList.css
src/organisms/UserList.tsx
src/pages/AppContainer.tsx
src/templates/AppComponent.css
src/templates/AppComponent.tsx
yarn.lock

- for wide screen
- for narrow screen

Support response

---

src/organisms/Menu.css

support animation on menu toggle

---

.github/workflows/main.yml
package.json

- add main.yml for GitHub Actions

add main.yml for GitHub Actions

---

README.md

- Add a badge on README.md to indicate the latest CI status

add badge to indicate CI status on README.md

---

.github/workflows/main.yml
package.json

- lint on CI
- use cache in CI for speed up

Support lint

---

src/molecules/Timer.tsx
src/organisms/Session.tsx
src/templates/AppComponent.tsx
yarn.lock

Disable start/pause button until the user is 2

---

src/molecules/Interval.tsx

Restrict min interval to 1 sec

---

src/pages/AppContainer.tsx

- remove some `event: React.MouseEvent<HTMLElement>` that are not used

remove unused parameter

---

src/pages/AppContainer.tsx
src/utils/cookie.tsx

Follow https://github.com/pankona/mobu/pull/20
Currently the cookie will be refreshed when browser closed. This PR changes to keep it.

Cookie keeps when browser closed

---

yarn.lock

update dependencies by yarn upgrade

---

yarn.lock

yarn upgrade react-scripts

---

.github/workflows/codeql-analysis.yml

Follow updated branch strategy

---

.eslintrc.json
package.json
src/atoms/Checkbox.tsx
src/atoms/Emoji.tsx
src/atoms/MenuIcon.tsx
src/molecules/User.tsx
src/organisms/Menu.tsx
src/pages/AppContainer.tsx
src/utils/cookie.tsx
yarn.lock

- Introduce config file for eslint
- Fix detected warnings

introduce eslintrc.json and fix lint warnings

---

src/atoms/Checkbox.tsx
src/molecules/SoundConfig.tsx
src/organisms/Session.tsx
src/pages/AppContainer.tsx
src/templates/AppComponent.tsx

Refs: https://qiita.com/Yametaro/items/814f40d08e9d30584e20
- Use `IntrinsicElements` for shorter code

use JSX.IntrinsicElements for Checkbox component

---

src/atoms/Button.css
src/atoms/Button.tsx
src/molecules/Timer.tsx
src/organisms/Session.tsx
src/pages/AppContainer.tsx
src/templates/AppComponent.tsx

- reduce buckets relay by using
- props object
- IntrinsicElements["button"]
- reduce redandunt css

[RFC] shorter code by reducing bucket relay

---

src/pages/AppContainer.tsx

Standardize style to use `React.useState`

---

README.md
src/organisms/Menu.tsx

`mobu` is already not a pankona's personal project. It should be a world wide project and should be managed by organization. 😌

Update link to `mobu`, it is an organization now

---

src/atoms/Button.css

Hi, it's a great app! 👋 
I got a touch the app for a while and I thought it would be better off to buttons have a background color when it's hovered.
So I tried to add it. What do you think of this? Thanks!

Colorize the buttons for when it's hovered

---

package.json
src/atoms/Form.tsx
yarn.lock

Resolves: https://github.com/mobu-of-the-world/mobu/pull/267
- do `yarn prettier:fix` to fix prettier warnings

Fix prettier warnings

---

.github/workflows/dependency-review.yml

@mobu-of-the-world/committers  Hi all!
https://github.com/actions/dependency-review-action is a GitHub official action that reviews depedencies known vulnerabilities.
I'd like to use this here~

Introduce actions/dependency-review-action

---

src/userList/User.module.css
src/userList/UserList.module.css

Clarify draggable in li layer

---

src/App.tsx
src/common/Emoji.tsx
src/common/Form.tsx
src/common/Text.tsx
src/common/TextInput.tsx
src/header/HamburgerMenu.tsx
src/header/Menu.tsx
src/header/MenuIcon.tsx
src/header/index.tsx
src/session/Interval.tsx
src/session/Session.tsx
src/userList/User.tsx
src/userList/UserList.tsx
src/userList/UserRegister.tsx

The syntax annoy to me. And it looks ancient now.  🗿 
https://github.com/facebook/create-react-app/pull/8177

Drop ancient style of `React.FC`

---

src/common/storage.ts
src/common/timerHooks.ts
src/session/Session.tsx
src/session/SoundConfig.tsx
src/session/Timer.tsx

Current  timer has most complexity logics rooted on React/useRef/setInterval tech stacks.
So I have tried to refactor with custom hook, it hide the useRef and record/clear intervals. It makes easy `pausing`.
Honestly, I don't have strong confident, but looks working!⏲️ 
refs:
* https://overreacted.io/making-setinterval-declarative-with-react-hooks/
* https://usehooks-ts.com/react-hook/use-interval

⏲️ Refactor complex timer with custom hook

---

src/footer/footer.module.css
src/index.css

Adjust link color and the decorations

---

.github/workflows/main.yml

https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
https://dev.classmethod.jp/articles/caching-dependencies-in-workflow-execution-on-github-actions/
https://www.voorhoede.nl/en/blog/super-fast-npm-install-on-github-actions/

Improve CI with dropping needless `setup` job

---

index.html
src/App.module.css

It is not specified any fonts, So different looks will be shown with user environment,
How about to specify font family?
[inconsolata](https://fonts.bunny.net/family/inconsolata) is one of my favorite. However other styles are okay if it is friendly for developers. (e.g Source Code Pro, IBM Plex, etc)
NOTE: Intentionally omitted fallback fonts.
Before
---
After
---

Specify font family

---

CONTRIBUTING.md
README.md

Personally I prefer to provide README for users and gathers developer notes into CONTRIBUTING.md.
@pankona How do you think?

Move development section to specialized doc

---

src/common/listHelpers.test.ts
src/common/listHelpers.ts
src/userList/UserList.tsx

Updates https://github.com/mobu-of-the-world/mobu/pull/430
Backports https://github.com/mobu-of-the-world/emobu/pull/216

Fix and improve Drag and Drop helper

---

.eslintrc.yml
package-lock.json
package.json

Preparation part of https://github.com/mobu-of-the-world/mobu/pull/866#issuecomment-1476311065

Deprecate, the deprecater

---

.eslintrc.yml
package-lock.json
package.json
src/common/usersContexts.tsx
src/session/Interval.tsx
tsconfig.base.json
tsconfig.json

Import https://github.com/mobu-of-the-world/emobu/pull/292 and https://github.com/kachick/action-typescript-template/pull/313 to close #866 
See https://github.com/kachick/action-typescript-template/issues/287 for further detail

Migrate to TypeScript 5

---

.eslintrc.yml
src/common/timerHooks.ts

References
* https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/
* https://github.com/typescript-eslint/typescript-eslint/tree/131ae664bf2024bfa43af69ee21efbe2b7fd0473/packages/eslint-plugin/src/configs may be much helpful
* 🇯🇵 https://zenn.dev/cybozu_frontend/articles/ts-eslint-v6-guide

Update usage of typescript-eslint to v6 era
