mobu-of-the-world/mobu

src/molecules/Interval.tsx
src/organisms/Session.tsx
src/pages/AppContainer.tsx
src/templates/AppComponent.tsx

Why
---
I often use this tool, then all teammates says `Why handling seconds? Hmm... we want to use 30 minutes then ... so ... 1800 seconds is the correct value!`
This is needless step 😄 
When I implemented current code in https://github.com/pankona/mobu/pull/8, handling seconds is so useful to ensure behavior, it is just a development reason.
Now is the time to change it, I think. 🕐 
Before
---
After
---

Changing interval as minutes instead of seconds

---

src/molecules/Timer.tsx
src/organisms/Session.tsx
src/pages/AppContainer.tsx
src/templates/AppComponent.tsx

Seeing the reminder, I implemented the initial idea of iteration counter (*1) which is indicated in https://github.com/pankona/mobu/issues/25.
The counter is displayed with label `iteration: ` between the time counter and `Start/Pause` button.
`Reset` will set the counter to 1 as it sets elapsed time to 00:00:00.
This might not be an optimal solution but I created a PR to illustrate the use case.
*1: Originally I used the expression "interval counter" but thought twice as it might be confused the time width(e.g. "25 / 30 minutes")

add an iteration counter (#25)

---

src/pages/AppContainer.tsx
src/utils/cookie.tsx

- Store sound config in a cookie on change its state not to lose it on browser reloading

store sound config in cookie

---

src/atoms/Emoji.tsx
src/pages/AppContainer.tsx

I personally prefer this style. TypeScript never in case prevents missing implementation for enums.

Prevent missing case pattern with never typing

---

.eslintrc.json
src/atoms/Emoji.tsx

I agreed https://www.kabuku.co.jp/developers/good-bye-typescript-enum.
So avoiding enum and using const will be better, I think.

Avoid to use TypeScript enum

---

src/pages/AppContainer.tsx

Currently validating the interval minutes with the input field `min` restriction.
It basically works in the ⬆️ and ⬇️ .
But directly inputting `0`, or copy and paste `-7` will be accepts by mobu. 
it is user fault. But we should consider to provide enterprise edition of mobu. These loopholes should be prevented 😤

Validate to input interval is positive number

---

src/atoms/Text.css
src/pages/AppContainer.tsx

`mobu` handles users as just a string. Then the string having whitespaces, they will be handled as another user.
It might be acceptable spec, but currently showing them as same user in view.
Before
---
It is a CSS issue, this PR fixes it.
After
---
And I can't think of usecases of padding whitespaces for start and end. So this PR trim them.

Prevent to show same users with inputting whitespaces

---

.github/dependabot.yml

https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#reviewers
Now, we are team!

Assign maintainers as reviewer instead of by name

---

public/index.html

* Problem
* `yarn start` opens your browser
* The browser warns `Manifest: Line: 1, column: 1, Syntax error.`
* Solution
* Don't require a missing file which is resolved as index.html

Fix `Manifest: Line: 1, column: 1, Syntax error.` error

---

package.json

* Problem: `yarn start` creats new browsr tab to open http://localhost:3000/
no matter how many tabs you have opened that page
* Solution: Don't add automatically but just show a message to open the URL.

Don't open browser tab every time when you restart

---

src/pages/AppContainer.tsx

* Problem: You can't input username with space like "7 days to die" or "Vim script"
* It transforms into "7daystodie" or "Vimscript", which do not make sense
* Solution: Don't remove spaces yours input

Trivial bugfix: don't prohibit username with spaces

---

src/atoms/TextInput.css
src/molecules/Interval.tsx
src/organisms/Session.tsx
src/pages/AppContainer.tsx

* Current `Interval` form has a bug. ~So I wanted to fix it.~
* ~`onIntervalChange` in `React.useCallback` has a dependency with `intervalSeconds`, but it doesn't pass to the method as second argument.~
* It causes that a user can't change the interval minute even if he/she changes the form.
* You can confirm the bug below. 
* OK, the above bug should be fixed. But... really should we enable to change the interval after starting the timer? I thought 'No'.
* If the timer is 1:59 and a user change the form to 2 minutes from 1 minute, the time never stop. It matters.
* So I disabled the form after the timer is stared.
* How can I disable the form?
* I felt that using the `IterationCount` is natural. when a user in an iteration, he/she can't change the interval.
* Therefore I changed the …

[Suggestion]Disable interval after the timer is started

---

src/atoms/Emoji.css

Components should not have styles that define how the component be displayed in parent components, like margin.
Referable article: https://zenn.dev/seya/articles/09545c7503baa4

Use padding in atom components instead of margin

---

package.json

Hello 👋 
This is a cosmetic change though, I moved the packages in `devDependencies` to `dependencies` because it's not necessary to categorize for an application that is built on create-react-app. It's okay to have all packages under `dependencies`.
**Refs**
- https://github.com/facebook/create-react-app/issues/2696
- https://stackoverflow.com/questions/44868453/create-react-app-install-devdepencies-in-dependencies-section
- https://scrapbox.io/ohbarye/Dependencies_in_Create_React_App

Move packages in devDependencies to dependencies

---

package.json

I found some packages that are used only in build time specified as 'dependencies' in package.json. This PR moves them to 'devDependencies'.

Move packages for development to devDependencies

---

package.json
src/pages/AppContainer.tsx
yarn.lock

Closes: https://github.com/mobu-of-the-world/mobu/pull/277
- Fix eslint error caused by bumping react-scripts to 5.0.0
- Single parameter generics cannot declare in jsx (tsx)
- A comma after the type parameter resolves the issue. Refs: https://github.com/Microsoft/TypeScript/issues/15713#issuecomment-499474386

Bump react-scripts to 5.0.0

---

.github/dependabot.yml

dependabot can track GitHub Actions updates.
The example is https://github.com/test-unit/test-unit/pull/188 => https://github.com/test-unit/test-unit/pull/215
We could got actions/checkout updates if introduced this.

Track github-actions updates by dependabot

---

.eslintrc.json
package-lock.json
package.json
src/session/Timer.tsx
src/session/timeHelpers.test.ts
src/session/timeHelpers.ts

Current formatting elapsed time has 2 issues.
* Bug: It calls Date constructor with given second as a milliseconds, it makes unexpected time if given seconds is large number.
* Not good: Using String.prototype.substr(), it is a deprecated method.
So this PR does...
* Prevent to use deprecated methods anymore, it checked in eslint plugin
* Add tests
* Fix the formatting method

Fix around elapsed time formatter

---

src/footer/footer.module.css
src/index.css

Currently footer always apears itself. It makes annoy especially in mobile view. So this change makes moderate footer, it will only be shown when scrolled.
⬇️

Moderate footer

---

src/session/Timer.tsx

How about to use object (hash map) to choice alert message?
I think this is same with using switch statement from the perspective of type safety.

use object (key is type safe) to choice alert message rather than switch

---

src/session/Interval.tsx
src/session/Session.tsx

I feel annoy when touching around timers. Because the manual test taking many hours caused on min duration is 1 minute.
So this PR provide as a debug mode. We can specify `seconds` with the query params. Without it, keeps current behaviors.
I have implemented the feature in https://github.com/kachick/mobu-elm as a UI. However URL based custom will fit for this mobu. I guess.
This might help to tackle https://github.com/mobu-of-the-world/mobu/issues/484

Implement unit selector to improve timer development

---

.eslintrc.json
.github/dependabot.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependency-review.yml
.github/workflows/main.yml
.vscode/extensions.json
.vscode/settings.json
README.md
dprint.json
package-lock.json
package.json
renovate.json
src/common/constants.ts
src/common/cssHelpers.test.ts
src/common/cssHelpers.ts
src/common/usersContexts.tsx
src/header/Menu.tsx
src/index.tsx
src/session/Interval.tsx
src/session/Session.tsx
src/session/SoundConfig.tsx
src/session/Timer.tsx
src/userList/UserList.tsx
src/userList/UserListHelpers.ts
src/userList/UserRegister.tsx
tsconfig.json

dprint vs prettier
---
Both have the strongness. Prettier has strong opinion and huge community, and looks stable behavior in these days.
dprint is pluggable, configurable and super fast ⚡.
Why dprint now?
---
Because prettier does not provide some options with their opinion.
A most negative to me is prettier/prettier#187.
I strongly agree eslint rule [no-mixed-operators](https://eslint.org/docs/latest/rules/no-mixed-operators).
At least, added parenthesis should not be removed by formatter if it was coder wanted.
However no option exists when using prettier.
It is a blocker to me especially developing around timer logics as #486.
Dprint is frequently developing now. So some style can't be adjusted to prettier does well.
But I 👍 for their decisions and I think it is enough ready to be …

Integrate dprint to enable `no-mixed-operators` in eslint

---

package.json

* In npm scripts. `pre*` and `post*` runs before and after the runner. 
* noEmit is already clarified in tsconfig.json https://github.com/mobu-of-the-world/mobu/blob/f4f4019a71e19f5f04eb3e04f435253ef821b48e/tsconfig.json#L9
ref: https://docs.npmjs.com/cli/v8/using-npm/scripts

Clarify tsc is a prebuild requirement

---

.github/workflows/dprint.yml
.github/workflows/main.yml

Extracted dprint CI from main. It is fast, other main jobs needs npm install. It is annoy to take time even if changing documents,

Skip needless CIs

---

src/index.css

This backports https://github.com/mobu-of-the-world/emobu/commit/ff837ded03fa9185df020f17012fedbd42ec5f52
Update #133 and #448
Currently mobile device hides the footer with the handling vh. So I have changed to use dvh to fix the issue. I have checked my Pixel 6a and iPad Pro.
I don't set any fallback styles because this tool should be used by edge devs 😬 
ref: 🗾 https://coliss.com/articles/build-websites/operation/css/large-small-dynamic-viewports.html, https://zenn.dev/futa/articles/90d7410650a73e, https://zenn.dev/moneyforward/articles/svh-dvh-lvh-for-all-browser

Prefer dvh rather than vh for mobile view especially iOS

---

CONTRIBUTING.md
package-lock.json
package.json

tsx is based on esbuild
I think we can drop ts-node since dropped jest in #725

Replace ts-node with tsx

---

.github/dependabot.yml

Since enabling automerge, I don't track them. If CI failed, we can know them easy. @pankona How do you think?

Disable to assign reviewers for dependabot PRs

---

README.md

This doesn't change how it looks like, but makes it easier for ourselves to edit.

README.md: ~Makes it easier to edit~ Regenerates contributors

---

.github/renovate.json
README.md
dprint.json
public/404.html
src/session/Interval.module.css

- **`npx dprint config add g-plane/malva`**
- **`npx dprint config add g-plane/markup_fmt`**
- **`npx dprint config add g-plane/pretty_yaml`**
- **Uninstall prettier plugin**
- **Add some settings to keep current behavior as possible**
- **`npx dprint fmt`**
- **Drop needless annotation since dropped prettier**
- **Add renovatebot config for updating dprint WASM plugins**
Make better integrations since https://github.com/mobu-of-the-world/mobu/pull/489

Replace dprint prettier plugin with WASM plugins

---

index.html
package-lock.json
package.json
src/index.tsx

- **`npm uninstall ress`**
- **Replace ress with modress**
Closes #1617
I think this is relaetd to following issues
- https://github.com/tsconfig/bases/pull/284
- https://github.com/filipelinhares/ress/pull/17

Fix updating error of ress with moduleDetection=false
